export const IS_LOADING = "IS_LOADING"

export const IS_USER_LOGIN_LOADING = "IS_USER_LOGIN_LOADING"
export const USER_LOGIN = "USER_LOGIN"
export const IS_USER_LOGIN_ERROR = "IS_USER_LOGIN_ERROR"

export const IS_USER_SIGNUP_LOADING = "IS_USER_SIGNUP_LOADING"
export const USER_SIGNUP = "USER_SIGNUP"
export const IS_USER_SIGNUP_ERROR = "IS_USER_SIGNUP_ERROR"